remote_theme: daviddarnes/alembic

navigation_header:
  Home: /
  Project 1: /P1_SLR/P1_SLR.html
  Project 2: /P2_Glacier/Glacier.html
  Project 3: /P3_STEMAA/STEMAA.html
  Project 4: /P4_AACBI_L6/L6.html
  Project 5: /P5_VAHabMap/VaHabMap.html
  Project 6: /P6_FishFinder/FF.html
